version: '3'

services:
 postgres:
   image: 'postgres:14'
   restart: always
   environment:
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: myverysecretpassword
     POSTGRES_DB: breeders
   logging:
     options:
       max-size: 10m
       max-file: "3"
   ports:
     - '54320:5432'
   volumes:
    #  - ./db-data/postgres:/var/lib/postgresql/data
     - ./sql/postgresql.sql:/docker-entrypoint-initdb.d/create_tables.sql
